### ISSUE TITLE
Either "expected folder" or "expected code" should be required in DatadirTestsFromDirectoryProvider

### ISSUE THREAD

**Issue by odinuv** [keboola/datadir-tests#19]
In this commit https://github.com/keboola/processor-remove-empty-files-and-folders/pull/3/commits/4100e401b7e2fd6bde07ace2703d4a9315ed81e0 there is not `expected` folder for `tests/functional/blank-file-with-empty-lines/` and the test is passing

**Comment by tomasfejfar** [comment]
That is an expected behavior. Only things that are specified are tested. To test that the folder is empty you'd need to create an empty `/expected/data/out` directory and `.gitkeep` in it. Why do you think that's unexpected? 

Relevant code: https://github.com/keboola/datadir-tests/blob/master/src/DatadirTestsFromDirectoryProvider.php#L88-L93

**Comment by odinuv** [comment]
it's like an assert without the expected value, so i would probably expect this:

````
        if (file_exists($outTemplateDir)) {
            if (is_null($expectedReturnCode)) {
                $expectedReturnCode = 0;
            }
            $expectedOutputDirectory = $outTemplateDir;
        } else {
            throw "No output directory specified"
        }
```

**Comment by tomasfejfar** [comment]
You don't need to check expected out directory contents. There may be only return value check as seen here in tests:

https://github.com/keboola/datadir-tests/tree/master/tests/functional/006-expected-internal-error/functional

**Comment by odinuv** [comment]
and if neither of expected or expected-code is present? 

(it would actually make more sense if expected-code was expected/code)

**Comment by tomasfejfar** [comment]
> (it would actually make more sense if expected-code was expected/code)

That I agree. Not sure it's worth the hassle to change. 

> and if neither of expected or expected-code is present?

Oh, yes, that's the actual bug! Thanks. Generally that's also valid - you can also expect certain stdout/stderr output using different providers, but for `DatadirTestsFromDirectoryProvider` it's an erroneous situation.

**Comment by odinuv** [comment]
> That I agree. Not sure it's worth the hassle to change.

no it's not
at least not now
