### ISSUE TITLE
Test should fail early if it's expected to fail but returns 0

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/datadir-tests#5]
Mám test, který má vyfailovat (`expected` folder chybí), ale skript dojede až na diff a vyhodí chybu tam.

https://github.com/keboola/datadir-tests/blob/e7aefe431299014eccf653bfd3cf6623b7ec2526/src/datadir-tests#L89

Podmínka `$isExpectedToFail` by se měla vyhodnocovat ještě před vyhodnocením exitCode procesu

https://github.com/keboola/datadir-tests/blob/e7aefe431299014eccf653bfd3cf6623b7ec2526/src/datadir-tests#L65

**Comment by odinuv** [comment]
to by znamenalo, ze skoncil exitcodem 0, coz je ale spatne

**Comment by ondrejhlavacek** [comment]
No vždyť přesně, to by ten test runner měl zachytit

**Comment by odinuv** [comment]
vsak to zachyti - tak, ze nesedi diff. Tim, ze ty podminky prehodis si vubec nepomuzes

**Comment by ondrejhlavacek** [comment]
Diff tam vůbec nemá význam, expected folder tam není a zachycení diffem je side effect, kterej ti navíc dá blbou hlášku. Mělo by ti to říct, že test nevyfailoval, a skončit chybou.

**Comment by odinuv** [comment]
no tak se to proste musi prepsat, aby to resilo vsechny 4 stavy:
nemelo failnout a nefailnulo -> diff
melo failnout a failnulo -> ok
melo failnout a nefailnulo -> chyba
nemelo failnout a failnulo -> chyba

**Comment by ondrejhlavacek** [comment]
No vždyť. Tím přehozením podmínky jsem myslel, to, že v bloku https://github.com/keboola/datadir-tests/blob/e7aefe431299014eccf653bfd3cf6623b7ec2526/src/datadir-tests#L65 se to už nevyřeší a musí se jít o úroveň vejš.

**Comment by tomasfejfar** [comment]
Máš pravdu. Mrknu na to.
