### ISSUE TITLE
Fail always on internal error

### ISSUE THREAD

**Issue by Halama** [keboola/datadir-tests#8]
Now tests pass even if application error is thrown instead of user error.
Imho internal error should never been expected in tests.

**Comment by tomasfejfar** [comment]
Do you have an example, pls?

**Comment by tomasfejfar** [comment]
What I could do is add an optional "expected" and/or "expected-code" file, with expected output and compare that with the actual output. That would allow you to test even for application errors if need be.

**Comment by tomasfejfar** [comment]
The current behavior is used in the wild btw:

```
processor-select-columns (master)
λ dcr dev /bin/bash
root@23a69e128b29:/code# php tests/run.php
Test /code/tests/csv-params
Test /code/tests/different-columns-order-in-different-files
Test /code/tests/escaped-and-newline
Test /code/tests/invalid-config-property
Failed as expected (1): Invalid configuration: Unrecognized option "columns_xxx" under "parameters"
Test /code/tests/missing-column
Failed as expected (1): Column doesnotexist not found.
Test /code/tests/missing-config-file
Failed as expected (2): Config file not found <-----------------------------------
Test /code/tests/missing-manifest
Failed as expected (1): Table sample1.csv does not have a manifest file.
Test /code/tests/missing-manifest-property
Failed as expected (1): Invalid configuration: The child node "columns" at path "parameters" must be configured.
Test /code/tests/multiple-columns
Test /code/tests/simple
Test /code/tests/sliced
```

**Comment by Halama** [comment]
Yes there is a example https://travis-ci.org/keboola/processor-flatten-folders/builds/385605023#L952 https://github.com/keboola/processor-flatten-folders/commit/e05a5764f81d8d788e2139e0efe011fb0c020013

**Comment by Halama** [comment]
I am not sure about testing internal errors.  But that `expected-code` could solve it too. Maybe with default `expected-code` set to `0`.

**Comment by odinuv** [comment]
+1 for expected code (i'd set default to 1, 0 is not needed (must have a result) and would be bwd compatible

**Comment by Halama** [comment]
sorry, i thought `1` as default
