### ISSUE TITLE
Allow testing of configs with env dependencies

### ISSUE THREAD

**Issue by tomasfejfar** [keboola/datadir-tests#9]
Currently datadir-tests are unusable for any use case where you need to supply ENV from outside. (workaround: https://github.com/keboola/aws-s3-writer/pull/1)

**Comment by ondrejhlavacek** [comment]
v tom writeru ale ani datadir tests smysl moc nedávaj, nebo na co bys to tam použil?

**Comment by tomasfejfar** [comment]
Jasně, chápu, jak to myslíš. Já je vidím pořád trošku dál, než jsou teď. Prakticky jako "dev" verzi toho pustit job v KBC. 

Více méně bych v nich otestoval scénáře co tam máš v ExceptionsFunctionalTest a UploadToRootTest. Ale úplně jako black-box testing. Dáš tomu data a config a na druhým konci zkontroluješ, že výstupy sedí (a nemusí být jen výstupy v datadiru, ale obecně, že "se svět změnil podle očekávání").

**Comment by ondrejhlavacek** [comment]
Takhle to dává smysl, :+1:

**Comment by tomasfejfar** [comment]
Protože původně to bylo "sedí/nesedí datadir". Teď už to je "sedí/nesedí + očekáváné failnutí". Očividně by bylo potřeba ještě "sedí/nesedí + očekávané failnutí + správný druh failnutí". A z původního diffu souborů se to vyvíjí víc k assertování dalších věcí. 

Dělat všechny tyhle testy integračně v KBC mi nepřijde dobrý nápad. A nemít to otestované taky ne.

**Comment by tomasfejfar** [comment]
^^ super :)

**Comment by tomasfejfar** [comment]
Closed via #12 and others
